CREATE DATABASE IF NOT EXISTS saviynt;
USE saviynt;

CREATE TABLE IF NOT EXISTS Customers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  profilePic LONGTEXT
);
